- hosts: web
  tasks:
    - name: Update the system with required packages
      shell: yum -y update && \
             yum clean all && \
             yum -y install epel-release && \
             yum clean all

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: latest 
      with_items:
        - httpd
        - php

    - name: Update inde.html file
      shell: cat /etc/hostname >> /var/www/html/index.html